### ISSUE TITLE
verbose stack Error: radish34@1.0.0 test: `NODE_ENV=test jest --verbose --runInBand --forceExit`

### ISSUE THREAD

**Issue by marsrobertson** [eea-oasis/baseline#254]
### Running the demo
https://github.com/ethereum-oasis/baseline/tree/master/examples/radish34

`make && make start && make test`

### Console output

```
  Sender creates Agreement, signs it, sends to recipient, recipient responds with signed Agreement
    ✕ encountered a declaration exception (1ms)

  ● Sender creates Agreement, signs it, sends to recipient, recipient responds with signed Agreement › encountered a declaration exception

    TypeError: Cannot read property 'substring' of undefined

      73 |   const recipient = getOrgSettings('supplier1');
      74 |   const recipientAddress = recipient.address;
    > 75 |   const recipientAddressPadded = `0x000000000000000000000000${recipientAddress.substring(2)}`;
         |                                                                                ^
      76 |   const name = `CO-${Math.floor(1000 + Math.random() * 10000)}`;
      77 |   const prevId = `CO-${Math.floor(1000 + Math.random() * 10000)}`;
      78 |   const namePadded = '0x000000000000000000434f2d31323334';

      at Suite.<anonymous> (__tests__/agreement.test.js:75:80)
      at Object.<anonymous> (__tests__/agreement.test.js:72:1)

Test Suites: 2 failed, 2 total
Tests:       16 failed, 15 passed, 31 total
Snapshots:   0 total
Time:        53.979s
Ran all test suites.
Force exiting Jest: Have you considered using `--detectOpenHandles` to detect async operations that kept running after all tests finished?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! radish34@1.0.0 test: `NODE_ENV=test jest --verbose --runInBand --forceExit`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the radish34@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/m/.npm/_logs/2020-11-06T21_09_31_501Z-debug.log
make: *** [test] Error 1
```

### Debug log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'test' ]
2 info using npm@6.14.6
3 info using node@v12.18.4
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle radish34@1.0.0~pretest: radish34@1.0.0
6 info lifecycle radish34@1.0.0~test: radish34@1.0.0
7 verbose lifecycle radish34@1.0.0~test: unsafe-perm in lifecycle true
8 verbose lifecycle radish34@1.0.0~test: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/m/Code/baseline/examples/radish34/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
9 verbose lifecycle radish34@1.0.0~test: CWD: /Users/m/Code/baseline/examples/radish34
10 silly lifecycle radish34@1.0.0~test: Args: [ '-c', 'NODE_ENV=test jest --verbose --runInBand --forceExit' ]
11 silly lifecycle radish34@1.0.0~test: Returned: code: 1  signal: null
12 info lifecycle radish34@1.0.0~test: Failed to exec test script
13 verbose stack Error: radish34@1.0.0 test: `NODE_ENV=test jest --verbose --runInBand --forceExit`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid radish34@1.0.0
15 verbose cwd /Users/m/Code/baseline/examples/radish34
16 verbose Darwin 19.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test"
18 verbose node v12.18.4
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error radish34@1.0.0 test: `NODE_ENV=test jest --verbose --runInBand --forceExit`
22 error Exit status 1
23 error Failed at the radish34@1.0.0 test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by sisco0** [comment]
The error is created because the _JSON_ object read is not constituted with the expected properties.
There is an assertion for this object to exist, leading to a successful read of the original configuration file.

When running the next piece of code in the test cited by the issue:
https://github.com/ethereum-oasis/baseline/blob/05921625071963a29aba7106b10e6c3de9e08f49/examples/radish34/__tests__/agreement.test.js#L73

There seems to be consulting the `config/config-supplier1.json` which contains these lines:
```json
{
  "rpcProvider": "http://ganache:8545",
  "organization": {
    "name": "Supplier 1",
    "role": 2
  },
  "addresses": {}
}
```

There not seems to be any `.address` property that could be parsed at the test line shown below:
https://github.com/ethereum-oasis/baseline/blob/05921625071963a29aba7106b10e6c3de9e08f49/examples/radish34/__tests__/agreement.test.js#L74

It seems that _Radish34_ is deprecated and has been replaced by the _Baseline Reference Implementation 1_ (BRI-1), as pointed out by the _Radish34_ [`README.md` head](https://github.com/ethereum-oasis/baseline/blob/629e0d2619f7e2256cd28220cfc1ff8c9f2bf201/examples/radish34/README.md)
